### ISSUE TITLE
Project & Tasks Functionality Enhancement

### ISSUE THREAD

**Issue by wasi0013** [wasi0013/PyTM#12]
**Is your feature request related to a problem? Please describe.**

### Project
- [ ] User will be able to start project tracking using a single command. 
- [ ] Check stats of particular project 
- [ ]  generate pdf/html reports for each project.
- [ ] For each project there will be at least one or, more milestones
- [ ] finish projects to mark all the tasks as completed
### Milestones

- [ ] basically  tag of strings that describe  particular tasks of the project. 
- [ ] The sum of all these milestones duration will be the total project length. 
- [ ] User will be able to check stats of each milestones. 
- [ ] start, pause, completed, abandoned status of milestones

**Describe the solution you'd like**
We will be using the library Click for cli for now (Perhaps with colorful outputs?)
